// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczPHx7VQiSO94ZqKKQ0T5QGG3Ke0c5oQ',
    appId: '1:599863726213:web:0cd59e48f581baf8a5d9ec',
    messagingSenderId: '599863726213',
    projectId: 'finbrain-80f71',
    authDomain: 'finbrain-80f71.firebaseapp.com',
    storageBucket: 'finbrain-80f71.firebasestorage.app',
    measurementId: 'G-76EHPN1S42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0V9f_Y6Sd4Ke3j4IcHfnMXjOSYJi7gBA',
    appId: '1:599863726213:android:74cc387fb3b7acc5a5d9ec',
    messagingSenderId: '599863726213',
    projectId: 'finbrain-80f71',
    storageBucket: 'finbrain-80f71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgih3uF_QRV9V2WPL-jQGpVvEbxjuAuY',
    appId: '1:599863726213:ios:9e2f2bc149654d88a5d9ec',
    messagingSenderId: '599863726213',
    projectId: 'finbrain-80f71',
    storageBucket: 'finbrain-80f71.firebasestorage.app',
    androidClientId: '599863726213-88haj4otr9km1631k3a2q7pq6pmvoph5.apps.googleusercontent.com',
    iosClientId: '599863726213-bsgvd2roniqfrd33mv83rnp9lcknmb45.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

}